### ISSUE TITLE
Определение версии прошивки

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#205]
```
version_os()(ndmc -c show version | grep version | head -1 | cut -d: -f2| tr -d ' ')
```
У меня не определяет, т.к. первая строка с version пустая
```
~ # ndmc -c show version

          release: 4.02.C.1.0-1
          sandbox: stable
            title: 4.2.1
             arch: mips

              ndm:
                exact: 0-7e1d38c
                cdate: 2 Oct 2024

              bsp:
                exact: 0-27d6a29f37
                cdate: 2 Oct 2024

              ndw:
              version:
             features: dual_image,wifi_button,usb_3,usb_3_first,led_control,wifi5ghz,vht2ghz,mimo2ghz,mimo5ghz,
                       atf2ghz,atf5ghz,wifi6,wifi_ft,wpa3,wsa5ghz,hwnat,sfp
           components: base,cloudcontrol,corewireless,dhcpd,dns-tls,ext,igmp,ipsec,l2tp,lang-en,lang-ru,mdns,
                       miniupnpd,ndmp,ndns,opkg,pingcheck,ppe,storage,trafficcontrol,tsmb,usb,wireguard

             ndw4:
              version: 4.2.4.24

     manufacturer: Keenetic Ltd.
           vendor: Keenetic
           series: KN
            model: Giga (KN-1011)
       hw_version: 11108000
          hw_type: router
            hw_id: KN-1011
           device: Giga
           region: EA
      description: Router

~ # ndmc -c show version | grep version
              version:
              version: 4.2.4.24
       hw_version: 11108000
~ # ndmc -c show version | grep version | head -1
              version:
```
Надёжнее как-то так (`opt/etc/ndm/ndm`):
```
version_os()(ndmc -c show version | grep -F 'version' | grep -oE '[0-9]\.[0-9\.]*[0-9]' | head -1)
```
