### ISSUE TITLE
Не работает после перезагрузки роутера

### ISSUE THREAD

**Issue by Noname-rus** [qzeleza/kvas#23]
Здравствуйте.
Использую:
- kvas 1.0 beta 21
- AdGuard Home.
- OpenVPN

Моя проблема аналогична #https://github.com/qzeleza/kvas/issues/17#issue-1438713708

Изначально был установлен kvas 1.0 beta 20 с dnsmasq.
Удалил старую версию:
`opkg remove kvas`
Перезагрузка

Установка и настройка AdGuard Home
```
bind_host: 192.168.0.1
bind_port: 8080
beta_bind_port: 0
users:
- name: xxxxxx
  password: xxxxxxx
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 127.0.0.1
  - 192.168.0.1
  port: 53
  statistics_interval: 7
  querylog_enabled: true
  querylog_file_enabled: true
```
Перезагрузка

Установка пакета kvas_1.0-beta_21_all.ipk
Kvas увидел предыдущий лист разблокировки, подтянул.
Ошибок на этапе установок нет.
Проверка работы связки - всё работает.
Перезагрузка

Отсутствует перенаправление в VPN  хостов из списка.
После `kvas adguard on` работоспособность восстанавливается.

Настройки роутера:
Параметры IP и DNS 
![1](https://user-images.githubusercontent.com/118457536/202496409-be518f73-6f1f-4f8d-a37a-fd2016b29a81.JPG)
Профили DNS
![2](https://user-images.githubusercontent.com/118457536/202498424-123a1277-c2d7-4c8b-b35e-4e6d5224c588.jpg)

Лог роутера (со строки 154 после выполнения `kvas adguard on`) [log.txt](https://github.com/qzeleza/kvas/files/10033291/log.txt)
debug сразу после перезагрузки [debug1.txt](https://github.com/qzeleza/kvas/files/10033293/debug1.txt)
debug после kvas adguard on [debug2.txt](https://github.com/qzeleza/kvas/files/10033296/debug2.txt)
